---
services:
  ##################
  ##### Raneto #####
  ##################
  # https://hub.docker.com/r/raneto/raneto
  raneto:
    # We don't recommend using the ":latest" tag
    # image: raneto/raneto:latest
    # Use explicit versions instead and monitor them
    image: docker.io/raneto/raneto:0.18.0
    container_name: raneto
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config:/opt/raneto/config
      - ./content:/opt/raneto/content
